### PR TITLE
Bump elm-html version, so that apps that depend on it don't get an old version

### PR DESCRIPTION
**Pull request by kcarnold**
This was resulting in an inscrutable error about trying to get 'arity' of 'undefined' (namely, VirtualDom.Attribute) in my code.

I haven't noticed any breakages from doing this, but I can't tell for sure.

### CODE REVIEW

**Comment by evancz** [comment]
I think the compiled code from the sidebar can overlap with the code generated by your program, leading to weird interactions. If my memory serves me well, this seems like it should not really be relevant unless you are building from source in a very particular way. What exactly is your situation? Does it seem like a better fix to somehow sandbox the sidebar code?

**Comment by kcarnold** [comment]
This happened on the binary release for me. Definitely sandboxing the sidebar code would be a better solution.

**Comment by jvoigtlaender** [comment]
The current version of the reactor now does have higher version bounds on `elm-html`, so I think this pull request can be closed.

The broader issue, that libraries depended on by the reactor's debugging mode as well as by the program running in the reactor might clash (different versions, unclear interference), is also covered here: https://github.com/elm-lang/elm-reactor/issues/104.

**Comment by evancz** [comment]
We are hoping to just have these things totally isolated in the next release, so this kind of thing won't be a problem anymore.

**Pull request closed without merging**
