### PR TITLE
Integrating elm-reactor-index

### PR DESCRIPTION
**Pull request by JustusAdam**
This is the integration step for the new and revamped elm-reactor index page. Source project can be found [here](https://github.com/JustusAdam/elm-reactor-index.git).

I've tried to rewrite as little code as possible even though I really want to lint the code and run stylish-haskell over it.

### CODE REVIEW

**Comment by JustusAdam** [comment]
PS: Please someone test that I didn't forget to add anything to the .cabal file. It happens so frequently.

**Comment by vilterp** [comment]
I've been in the middle of a big refactor of the debugger internals; will look at this ASAP this week!

**Comment by evancz** [comment]
I don't know why it's not showing up here, but I merged this into the `next` branch today. I made some style changes here and there, but overall, it was great! Thanks for getting this working and turning it into a PR! Excited to have this in the next release :)

**Comment by evancz** [comment]
Here's how things look right now:

screen shot 2015-08-13 at 1 56 12 pm

Thanks again for your hard work!

**Comment by JustusAdam** [comment]
Yes, very nice and pretty. 

Thanks for the screenshot btw. I tried installing the next branch earlier to have a look but Elm had trouble resolving the dependencies and so I couldn't.

**Comment by evancz** [comment]
No problem! Be aware of [this](https://github.com/elm-lang/elm-reactor/tree/next#building-from-source) when trying to build. It sounds like things on hackage changed unexpectedly, so I'll probably have to rebuild all of my stuff to see what people are running into.

**Comment by JustusAdam** [comment]
I don't think that's the issue I am having. Installing the compiler and elm-package in the lokal sandbox went down without a problem/
However elm-package has problems resolving the dependencies (there seems to be some versioning conflict) hence the issue elm-lang/elm-package#119 I opened.

**Pull request closed without merging**
