### PR TITLE
Migrate sidebar container to Elm

### PR DESCRIPTION
**Pull request by vilterp**
Now, JS makes a container overlaying the whole page, but everything inside that is Elm. For #106

### CODE REVIEW

**Comment by vilterp** [comment]
Icons not translating correctly in Safari
screen shot 2015-06-25 at 7 15 09 pm

**Comment by vilterp** [comment]
Html version seems to stutter a bit more (i.e. slider jumps between where mouse is and where reactor playback is) [new](http://youtu.be/4Pv6EpJn1dE) vs [old](http://youtu.be/zYgs9J3soaU).

**Comment by vilterp** [comment]
I guess this is because when you drag the slider,

1. browser renders it under your mouse
2. change event fires; picked up by Elm
3. Elm renders sidebar, including slider based on `scrubPosition`
4. Elm pushes out `scrubTo` port
5. in JS, RTS jumps module to that frame
6. (event processing ends)

theory: the browser is re-rendering the slider while the callback is being processed. Then, when the callback is done processing, slider is re-rendered at previous state before change event for next state is processed. Not sure how to fix this.

**Comment by evancz** [comment]
I didn't really like that things changed layout when that button was gone, so that's good!

With the transform tag, you probably need to say `-webkit-transform` and `-ms-transform` and `-moz-transform` and `-o-transform` to make sure it works everywhere. There was a pattern where browsers would do "vendor prefixes" on new CSS things that were not standardized yet. Chat me if this is confusing.

That stutter is interesting. I think we don't need to block on that. My desire would be to process fewer of the slider events so maybe we can jump a couple frames to make things appear smoother.

**Comment by evancz** [comment]
Maybe the issue is that the runtime should only be telling Elm about *new* events, not all changes.

**Comment by vilterp** [comment]
when scrolling the watches, you see a sidebar in Safari but not in Chrome. No idea why. Otherwise I think it's time to move on to other reactor improvements

**Comment by evancz** [comment]
Awesome, I'll try to get it reviewed tonight!

**Comment by evancz** [comment]
Awesome, this is looking great!

**Pull request merged**
